workspace: !ENV ${WORKSPACE}
redis_url: !ENV ${REDIS_URL}
supervisor_url: !ENV ${SUPERVISOR_URL}
worker_log_dir: !ENV ${WORKER_LOG_DIR}
workers:
  - user: !ENV ${USER}
    queues:
      - high
      - low
      - batch
